# API documentation configuration file
# Used for https://vipps.no/developer-pages
# This file will be fetched by the user's browser
# Do not store personal or confidental information in this file

# Short name of the API
apiShortName: SampleAPI

# This will appear as the title on the API page
apiLongName: Vipps Sample API

# Short introduction to the API
introduction: This is a short introduction of the API

# The name of the group in Vipps that is responsible for maintaining the code
# This does not appar on the page
owner: VippsAS

# GitHub url of the repository
githubRepo: https://github.com/vippsas/sample-api

# List of markdown files
# - title: Short name of the document to be displayed. (eg. Getting started)
# - slug: Used to identify the document, must be unique. (eg. getting-started)
# - description: Short text of what useful information is contained in the document. (eg. Start here if you plan to integrate with our API)
# - markdownUrl: Url to the markdown source file (eg. vipps-ecom-api/master/vipps-ecom-api.md)
# - githubUrl: (optional) Url to GitHub, where the user can make issues and PRs
resources:
  - title: Documentation
    slug: documentation
    description: All you need to know about the API
    markdownUrl: vipps-ecom-api/master/vipps-ecom-api.md
    githubUrl: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md

# External links to developer resources at the top of the documentation page
# Optional
linklist:
  - title: Getting Started
    url: https://github.com/vippsas/vipps-developers/blob/master/vipps-getting-started.md
  - title: Swagger
    url: https://vippsas.github.io/vipps-ecom-api/
