# API documentation configuration file
# Used for https://vipps.no/developer-pages
# This file will be fetched by the user's browser
# Do not store personal or confidental information in this file

# Short name of the API
apiShortName: Overview

# This will appear as the title on the API page
apiLongName: Overview

# Short introduction to the API
introduction: Overview of Vipps services

# The name of the group in Vipps that is responsible for maintaining the code
# This does not appar on the page
owner: VippsAS

# GitHub url of the repository
githubRepo: https://github.com/vippsas/vipps-developers

# List of markdown files
# - title: Short name of the document to be displayed. (eg. Getting started)
# - slug: Used to identify the document, must be unique. (eg. getting-started)
# - description: Short text of what useful information is contained in the document. (eg. Start here if you plan to integrate with our API)
# - markdownUrl: Url to the markdown source file (eg. vipps-ecom-api/master/vipps-ecom-api.md)
# - githubUrl: (optional) Url to GitHub, where the user can make issues and PRs
resources:
  - title: Introduction
    slug: introduction
    description: Information about test environment, test app and Vipps servers
    markdownUrl: vipps-developers/master/README.md
    githubUrl: https://github.com/vippsas/vipps-developers/blob/master/README.md
  - title: Get Started
    slug: get-started
    description: Get started guide for Vipps APIs
    markdownUrl: vipps-developers/master/vipps-getting-started.md
    githubUrl: https://github.com/vippsas/vipps-developers/blob/master/vipps-getting-started.md
  - title: Postman Overview
    slug: postman-overview
    description: An overview of Postman resources for all Vipps APIs.
    markdownUrl: vipps-developers/master/postman-overview.md
    githubUrl: https://github.com/vippsas/vipps-developers/blob/master/postman-overview.md
  - title: Design guidelines
    slug: design-guidelines
    description: These guidelines will help you use the Vipps payments
    markdownUrl: vipps-design-guidelines/master/README.md
    githubUrl: https://github.com/vippsas/vipps-design-guidelines/blob/master/README.md
  - title: Contact Us
    slug: contact
    description: Contact information for technical support
    markdownUrl: vipps-developers/master/contact.md
    githubUrl: https://github.com/vippsas/vipps-developers/blob/master/contact.md

# External links to developer resources at the top of the documentation page
# Optional
linklist:
  - title: Devloper portal
    url: https://portal.vipps.no
